### ISSUE TITLE
Statistics not working

### ISSUE THREAD

**Issue by kotorkovsciy** [kotorkovsciy/Telegram-wakatime-stats-bot#2]
Functions based on statistics do not work

 - OS: windows 10

**Error when trying to get statistics by language**:
```
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-10' coro=<Dispatcher._process_polling_updates() done, defined at C:\Users\Kovinjko_Nikita\Documents\Проекты\Telegram-wakatime-stats-bot\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py:407> exception=PermissionError(13, 'Процесс не может получить доступ к файлу, так как этот файл занят другим процессом')>
Traceback (most recent call last):
  File "C:\Users\Kovinjko_Nikita\Documents\Проекты\Telegram-wakatime-stats-bot\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "C:\Users\Kovinjko_Nikita\Documents\Проекты\Telegram-wakatime-stats-bot\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "C:\Users\Kovinjko_Nikita\Documents\Проекты\Telegram-wakatime-stats-bot\venv\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Users\Kovinjko_Nikita\Documents\Проекты\Telegram-wakatime-stats-bot\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "C:\Users\Kovinjko_Nikita\Documents\Проекты\Telegram-wakatime-stats-bot\venv\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Users\Kovinjko_Nikita\Documents\Проекты\Telegram-wakatime-stats-bot\handlers\stats.py", line 17, in cmd_stats_lang
    photo = await AnaliticStats.lang_stats(
  File "C:\Users\Kovinjko_Nikita\Documents\Проекты\Telegram-wakatime-stats-bot\scripts\analitic_stats.py", line 66, in lang_stats
    return await cls.statics(user_id, email, password, "languages")
  File "C:\Users\Kovinjko_Nikita\Documents\Проекты\Telegram-wakatime-stats-bot\scripts\analitic_stats.py", line 59, in statics
    remove(f"{cls.PATH_IMAGES}{user_id}_{theme}_stats.png")
PermissionError: [WinError 32] Процесс не может получить доступ к файлу, так как этот файл занят другим процессом: 'info/images/5343075356_languages_stats.png'
```

**Comment by kotorkovsciy** [comment]
close: 7868b927bef976d1265ed5e677bc4ffb5b2106e1
